- name: Install base packages
  ansible.builtin.package:
    name: "{{ base_packages + curl_package }}"
    state: present
  vars:
    base_packages:
      - git
      - unzip
      - tar
      - htop
    curl_package: "{{ ['curl-minimal'] if ansible_distribution == 'Amazon' else ['curl'] }}"

- name: Ensure app base directory exists
  ansible.builtin.file:
    path: "{{ app_base_dir }}"
    state: directory
    mode: "0755"
