server:
  port: 8090
spring:
  application:
    name: farmersmk-payment-service
  profiles:
    active: prod
management:
  endpoints:
    web:
      exposure:
        include: health,info
payment:
  mtn_mobile_money:
    phone_number: "+237675142175"
  crypto:
    usdt:
      network: "Tron(TRC20)"
      address: "TVMsNvsMk22oguXnxmZHDBoFYP8LPHaWx3"
