

services:
  farmersmk-auth-service:
    build:
      context: ./farmersmk-auth-service
      dockerfile: Dockerfile
    container_name: farmersmk-auth-service
    ports:
      - "8081:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  farmersmk-api-gateway:
    build:
      context: ./farmersmk-api-gateway
      dockerfile: Dockerfile
    container_name: farmersmk-api-gateway
    ports:
      - "8080:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  farmersmk-marketplace-service:
    build:
      context: ./farmersmk-marketplace-service
      dockerfile: Dockerfile
    container_name: farmersmk-marketplace-service
    ports:
      - "8088:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  farmersmk-user-service:
    build:
      context: ../services/farmersmk-user-service
      dockerfile: Dockerfile
    container_name: farmersmk-user-service
    ports:
      - "8082:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  farmersmk-mastercard-service:
    build:
      context: ../services/farmersmk-mastercard-service
      dockerfile: Dockerfile
    container_name: farmersmk-mastercard-service
    ports:
      - "8083:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  farmersmk-socialmediafacebook-service:
    build:
      context: ../services/farmersmk-socialmediafacebook-service
      dockerfile: Dockerfile
    container_name: farmersmk-socialmediafacebook-service
    ports:
      - "8084:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  farmersmk-socialmediatwitter-service:
    build:
      context: ../services/farmersmk-socialmediatwitter-service
      dockerfile: Dockerfile
    container_name: farmersmk-socialmediatwitter-service
    ports:
      - "8085:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  farmersmk-socialmediainstagram-service:
    build:
      context: ../services/farmersmk-socialmediainstagram-service
      dockerfile: Dockerfile
    container_name: farmersmk-socialmediainstagram-service
    ports:
      - "8086:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  farmersmk-notification-service:
    build:
      context: ../services/farmersmk-notification-service
      dockerfile: Dockerfile
    container_name: farmersmk-notification-service
    ports:
      - "8089:8080"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod




