version: '3.8'

services:

  auth-service:
    build: ./farmpro-auth-service
    container_name: farmpro-auth
    ports:
      - "8081:8081"

  marketplace-service:
    build: ./farmpro-marketplace-service
    container_name: farmpro-marketplace
    ports:
      - "8082:8082"

  api-gateway:
    build: ./farmpro-api-gateway
    container_name: farmpro-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - marketplace-service